name: Course Change Detection

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  push:
    branches:
      - main
    paths:
      - 'courses/**'

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    outputs:
      release-tag: ${{ steps.create-release.outputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%y.%m.%d')"
      
      - name: Create Release Tag
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=$(date +'%y.%m.%d')
          TAG="v$DATE-1"
          echo "::set-output name=tag::$TAG"
          echo "RELEASE_TAG=$TAG" >> $GITHUB_ENV

  create-release:
    needs: detect-changes
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.prepare-release.outputs.release-tag }}
          release_name: Release ${{ needs.prepare-release.outputs.release-tag }}
          draft: false
          prerelease: false

  detect-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - uses: actions/cache@v4
        id: cache-virtualenv
        with:
          path: ".virtualenv"
          key: "python-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}"

      - if: steps.cache-virtualenv.outputs.cache-hit != 'true'
        run: make --no-print-directory require-virtualenv

      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: "3.9"
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
      
      - name: Detect Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python3 tools/detect_changes.py