name: Conditional Daily Deployment Preparation (Weekdays Only)

on:
  schedule:
    # Runs at 9:00 AM GMT, Monday through Friday
    - cron: '0 9 * * 1-5'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.set_output.outputs.has_changes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated for Node.js 20 support

      - name: Fetch all tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* 

      - name: Install GitHub CLI
        run: |
          if ! gh --version &>/dev/null; then
            sudo apt update
            sudo apt install -y gh
          fi

      - name: Fetch the latest release
        id: latest_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASES=$(gh api repos/${{ github.repository }}/releases --paginate)
          LATEST_RELEASE=$(echo "$RELEASES" | jq -r '.[] | select(.draft == false and .prerelease == false) | .tag_name' | head -n 1)
          if [ -n "$LATEST_RELEASE" ]; then
            echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV
          fi

      - name: Check for changes
        id: check_changes
        run: |
          if [ -n "$LATEST_RELEASE" ]; then
            CHANGES=$(git diff --name-only "$LATEST_RELEASE"..main)
            if [ -n "$CHANGES" ]; then
              echo "::set-output name=has_changes::true"
            else
              echo "::set-output name=has_changes::false"
            fi
          else
            echo "::set-output name=has_changes::false"
          fi

      - name: Set output
        id: set_output
        run: echo "has_changes=${{ steps.check_changes.outputs.has_changes }}" >> $GITHUB_ENV
        outputs:
          has_changes: ${{ steps.check_changes.outputs.has_changes }}

  run-scripts:
    needs: check-for-changes
    if: needs.check-for-changes.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # Your additional steps here
