name: Conditional Daily Deployment Preparation (Weekdays Only)

on:
  schedule:
    # Runs at 9:00 AM GMT, Monday through Friday
    - cron: '0 9 * * 1-5'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.check_changes.outputs.has_changes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated for Node.js 20 support

      - name: Fetch all tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* 

      - name: Install GitHub CLI
        run: |
          if ! gh --version &>/dev/null; then
            sudo apt update
            sudo apt install -y gh
          fi

      - name: Fetch the latest release
        id: latest_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASES=$(gh api repos/${{ github.repository }}/releases --paginate)
          LATEST_RELEASE=$(echo "$RELEASES" | jq -r '.[] | select(.draft == false and .prerelease == false) | .tag_name' | head -n 1)

          if [ -n "$LATEST_RELEASE" ]; then
            echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV
          fi

      - name: Check for changes
        id: check_changes
        run: |
          if [ -n "$LATEST_RELEASE" ]; then
            CHANGES=$(git diff --name-only "$LATEST_RELEASE"..main)
            echo "$CHANGES"
            if [ -n "$CHANGES" ]; then
              echo changes found - changes true
              echo "has_changes=true" >> "$GITHUB_OUTPUT"
            else
            echo no changes - changes false
              echo "has_changes=false" >> "$GITHUB_OUTPUT"
            fi
          else
            echo no latest release - changes false
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          fi

  test-outputs:
    runs-on: ubuntu-latest
    needs: check-for-changes
    steps:
      - env: 
          HAS_CHANGES: ${{needs.check-for-changes.outputs.has_changes}}
        run: echo HAS_CHANGES:" $HAS_CHANGES"

      # Your additional steps here
  
  run-scripts:
    needs: check-for-changes
    if: ${{needs.check-for-changes.outputs.has_changes}} == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # Your additional steps here
